language: php

php:
  - 5.5
  - 5.6
  - 7
  - 7.1
  - hhvm

sudo: false

install: travis_retry composer install

before_script: composer install --prefer-source

script: composer ci

after_success:
  - if [[ "`phpenv version-name`" != "7.1" ]]; then exit 0; fi
  - vendor/bin/phpunit --coverage-clover coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache